# Generated by Django 6.0.4 on 2026-04-14 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('out_of_location', 'Out of Location'), ('out_of_time', 'Out of Time'), ('wrong_activity', 'Wrong Activity'), ('no_qr', 'No QR Code'), ('expired_subscription', 'Expired Subscription')], max_length=30)),
                ('action', models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('suspension', 'Suspension')], max_length=20)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='violation_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('violation', 'Violation')], max_length=20)),
                ('valid_location', models.BooleanField(default=False)),
                ('valid_time', models.BooleanField(default=False)),
                ('valid_activity', models.BooleanField(default=False)),
                ('valid_subscription', models.BooleanField(default=False)),
                ('officer_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('officer_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
