# Generated by Django 6.0.4 on 2026-04-14 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('stalls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='stalls.stall'),
        ),
        migrations.AddField(
            model_name='violation',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='violation',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violation',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='stalls.stall'),
        ),
    ]
