# Generated by Django 6.0.4 on 2026-04-14 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stalls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Municipality admin who recorded the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stalls.stall')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionRenewalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_sent_at', models.DateTimeField(auto_now_add=True)),
                ('days_before_expiry', models.IntegerField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_alerts', to='subscriptions.subscription')),
            ],
        ),
    ]
