# Generated by Django 6.0.4 on 2026-04-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('stalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalls.stallcategory'),
        ),
        migrations.AddField(
            model_name='locationcategory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_categories', to='locations.location'),
        ),
        migrations.AlterUniqueTogether(
            name='locationcategory',
            unique_together={('location', 'category')},
        ),
    ]
